name: max_trivia
description: Timed trivia game

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  web_socket_channel: ^2.2.0
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^2.4.0

flutter:
  fonts:
    - family: LexandDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
  uses-material-design: true
