// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvksK0MnPrQXONziWdPDJGVjK5H9830gE',
    appId: '1:209696384740:web:7550d540f17a8e3f6a6ef1',
    messagingSenderId: '209696384740',
    projectId: 'max-trivia',
    authDomain: 'max-trivia.firebaseapp.com',
    storageBucket: 'max-trivia.appspot.com',
    measurementId: 'G-NP8N45XEJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-LZnktg6wiXn8Qz2DzG5WD3cs6o6xj0s',
    appId: '1:209696384740:android:e7c4289bb59f08316a6ef1',
    messagingSenderId: '209696384740',
    projectId: 'max-trivia',
    storageBucket: 'max-trivia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_Mwpt1uorY3ii61QjL8YKXeF-kloszw',
    appId: '1:209696384740:ios:39afd31f4f898c0c6a6ef1',
    messagingSenderId: '209696384740',
    projectId: 'max-trivia',
    storageBucket: 'max-trivia.appspot.com',
    iosClientId: '209696384740-tb24djpg7fhma10mlkjq7b7lksbvir25.apps.googleusercontent.com',
    iosBundleId: 'com.maxshaberman.maxTrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_Mwpt1uorY3ii61QjL8YKXeF-kloszw',
    appId: '1:209696384740:ios:39afd31f4f898c0c6a6ef1',
    messagingSenderId: '209696384740',
    projectId: 'max-trivia',
    storageBucket: 'max-trivia.appspot.com',
    iosClientId: '209696384740-tb24djpg7fhma10mlkjq7b7lksbvir25.apps.googleusercontent.com',
    iosBundleId: 'com.maxshaberman.maxTrivia',
  );
}
